### ISSUE TITLE
changeset md 감지 이후 댓글 변경

### ISSUE THREAD

**Issue by yceffort-naver** [NaverPayDev/changeset-actions#14]
### 작업 내용

<img width="940" alt="image" src="https://github.com/user-attachments/assets/3c32f5d5-4cde-463e-898c-6b2d32c7fa05">

changeset 추가 된 이후에는 댓글이 변경되었으면 좋겠습니다!

> 버전 버튼을 다 없애버리고 확인되었습니다.. 이렇게 할까요? 🤔

**Comment by 2-one-week** [comment]
https://github.com/NaverPayDev/changeset-actions/issues/9 

에서 한번에 처리하겠습니다
