### ISSUE TITLE
깃헙 댓글 영문으로 수정 요청

### ISSUE THREAD

**Issue by yceffort-naver** [NaverPayDev/changeset-actions#9]
### 작업 내용

- https://github.com/NaverPayDev/hidash/pull/106#issuecomment-2484489415 와 같은 내용을 영문으로 수정하거나, 혹은 lang 값을 받아서 한국어/영어를 지원헀으면 좋겠습니다. (기본값 영어)
 - 댓글에 https://github.com/apps/changeset-bot 를 기반으로 만들어졌다고 아주 작게 나와있으면 좋겠습니다.

**Comment by 2-one-week** [comment]
https://github.com/NaverPayDev/hidash/pull/106#issuecomment-2484489415

이 형태랑 비슷하게 해서, 마크다운 이쁘게 짜보겠스므니다

**Comment by 2-one-week** [comment]
> 댓글에 https://github.com/apps/changeset-bot 를 기반으로 만들어졌다고 아주 작게 나와있으면 좋겠습니다.

detect add 같은 경우는 자체 구현인데..!

**Comment by 2-one-week** [comment]
음... 그러면 원하시는 방향을 잘 풀어보겠습니다 ㅋㅋㅋ

**Comment by npayolaf** [comment]
오 .. 아랍어 지원하는 그날까지 !!
